name: Windows-build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build_win_amd64:
    name: 'win64'
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: 'python/cpython'

      - name: Register MSVC problem matcher
        run: echo "::add-matcher::.github/problem-matchers/msvc.json"

      - name: Disable preinstalled python
        run: Remove-Item C:\Windows\py.exe

      - name: Build CPython
        run: .\PCbuild\build.bat -e -d -p x64
        timeout-minutes: 30

      - name: Checking dll
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install msys2
          msys2 -mingw64 -c "ldd /a/test-cpython-windows/test-cpython-windows/PCbuild/amd64/python.exe"

      - name: Display build info
        run: .\python.bat -m test.pythoninfo
      # - name: Tests
      #   run: .\PCbuild\rt.bat -p x64 -d -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0
