name: Windows-build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build_win32:
    name: 'Windows (x86)'
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
        repository: 'https://github.com/python/cpython'

      - name: Disable preinstalled python
        run: Remove-Item C:\Windows\py.exe

      - name: Build CPython
        run: .\PCbuild\build.bat -e -d -p Win32
        timeout-minutes: 30

      - name: Display build info
        run: .\python.bat -m test.pythoninfo
      # - name: Tests
      #   run: .\PCbuild\rt.bat -p Win32 -d -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-latest
    env:
      IncludeUwp: 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
        repository: 'https://github.com/python/cpython'

      - name: Register MSVC problem matcher
        run: echo "::add-matcher::.github/problem-matchers/msvc.json"

      - name: Disable preinstalled python
        run: Remove-Item C:\Windows\py.exe

      - name: Build CPython
        run: .\PCbuild\build.bat -e -d -p x64
        timeout-minutes: 30

      - name: Display build info
        run: .\python.bat -m test.pythoninfo
      # - name: Tests
      #   run: .\PCbuild\rt.bat -p x64 -d -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0
